### ISSUE TITLE
Access Denied

### ISSUE THREAD

**Issue by juanfernandes** [anwarishak/universal-vagrant#1]
Hi,

Wonder if you may be able to help me. I have followed your instructions, but when I go to http://localhost:8080/ I get Access Denied. 

Any ideas what I may have done wrong?

Juan

**Comment by anwarishak** [comment]
Hi — can you try and get more info on this?

Once your vagrant is up and running, open Terminal (or command line app) and type:

vagrant ssh

This logs you into the vagrant/Ubuntu machine. Once in, go to /var/www/default/logs and see the contents of the error log. This should give us some clues. So, in command line:

tail -50 /var/www/default/logs/error.log

If you copy/paste the error here, I can try and help.
